/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-10-08 13:35:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mp3upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <form action=\"upload\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<li><label>UserID : </label> <input type=\"text\" name=\"userid\"\r\n");
      out.write("\t\t\tplaceHolder=\"유저 아이디를 입력해주세요\"></li>\r\n");
      out.write("\t\t<li><label>제목 :</label> <input type=\"text\" name=\"title\"\r\n");
      out.write("\t\t\tplaceHolder=\"게시물제목을 입력해주세요\"></li>\r\n");
      out.write("\t\t<li><label>설명 :</label> <input type=\"text\" name=\"dsc\"\r\n");
      out.write("\t\t\tplaceHolder=\"노래에 대한 설명을 입력해주세요\"></li>\r\n");
      out.write("\t\t<li><label>장르 : </label> <select name=\"cate\">\r\n");
      out.write("\t\t\t\t<option value=\"댄스\">댄스\r\n");
      out.write("\t\t\t\t<option value=\"발라드\">발라드\r\n");
      out.write("\t\t\t\t<option value=\"팝\">팝\r\n");
      out.write("\t\t\t\t<option value=\"클래식\">클래식\r\n");
      out.write("\t\t\t\t<option value=\"락\">락\r\n");
      out.write("\t\t\t\t<option value=\"기타\">기타\r\n");
      out.write("\t\t</select></li> <br>\r\n");
      out.write("\t\t<li><label>파일 업로드</label> <input type=\"file\" name=\"file\"></li>\r\n");
      out.write("\t\t<li><label>img : </label> <input type=\"text\" name=\"img\"\r\n");
      out.write("\t\t\tplaceHolder=\"이미지 경로\"></li>\r\n");
      out.write("\t\t<li><label>가수 :</label> <input type=\"text\" name=\"artist\"\r\n");
      out.write("\t\t\tplaceHolder=\"가수이름\"></li>\r\n");
      out.write("\t\t<li><label>앨범 : </label> <input type=\"text\" name=\"albname\"\r\n");
      out.write("\t\t\tplaceHolder=\"앨범 제목\"></li> <br> <input type=\"submit\"\r\n");
      out.write("\t\t\tname=\"upload\" value=\"업로드\"> -->\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"upload\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-addon\"> UserID </span> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"userid\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"UserID\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-addon\"> Title </span> <input name=\"title\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"게시물 제목\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-addon\"> Artist </span> <input name=\"artist\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"가수이름\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"dsc\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"노래에 대한 상세정보를 입력해 주세요\" style=\"height: 120px;\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn btn-success btn-file\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-paperclip\"></i> Attachment <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"file\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-times\"></i> Discard\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-left\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-envelope\"></i> File Upload\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
